name: CI for simple-smt
on:
  push:
    branches: [ master ]
    tags: [ "*" ]
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest
    name: Run test suites
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Install nix
      uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Processes test
      run: nix develop --command cabal test
    - name: Z3 backend test
      run: nix develop --command cabal test Z3

  formatting:
    runs-on: ubuntu-latest
    name: Check formatting
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Install nix
      uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        nix shell nixpkgs#ormolu --command ormolu --mode check $(find . -name '*.hs')
