name: CI for simple-smt
on:
  push:
    branches: [ master ]
    tags: [ "*" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check formatting
    steps:
    - uses: actions/checkout@v3.1.0
    - name: Install nix
      uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: |
        nix shell nixpkgs#ormolu --command ormolu --mode check $(find . -name '*.hs')
